# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151124181010 on 2015-12-05 14:38
from __future__ import unicode_literals

import Bank.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField()),
                ('base', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('level', models.IntegerField(default=Bank.models.Level.nextLevel, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('image', models.ImageField(default='', upload_to='uploads/', verbose_name='Image')),
                ('question_id', models.CharField(default=Bank.models.Question.uidgen, help_text='This is auto-generated', max_length=8, primary_key=True, serialize=False)),
                ('answer', models.CharField(blank=True, max_length=20)),
                ('jumbled_answer', models.CharField(blank=True, max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.Level')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default=Bank.models.User.uidgen, help_text='This is auto-generated', max_length=8, primary_key=True, serialize=False)),
                ('screen_name', models.CharField(blank=True, default='', max_length=20)),
                ('unlocked_levels', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='hint',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.Question'),
        ),
    ]
