# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151124181010 on 2015-12-05 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='base',
        ),
    ]
