# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151124181010 on 2015-12-06 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_remove_hint_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(default='', upload_to=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bank.Level'), verbose_name='Image'),
        ),
    ]
